# fly.toml app configuration file generated for llamanager on 2025-03-06T09:09:58+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'llamanager'
primary_region = 'ord'
swap_size_mb = 1024

[build]

[env]
  API_PORT = '8081'
  DATA_DIR = '/volume'
  DB_FILE = '/litefs/database.db'
  INTERNAL_PORT = '8080'
  MANAGER_PORT = '8080'
  MODEL_DIR = '/models'

[processes]
  api = 'litefs mount -config /app/litefs.yml'
  manager = 'litefs mount -config /app/litefs.yml'
  worker = 'litefs mount -config /app/litefs.yml'

[[mounts]]
  source = 'llamanager_data'
  destination = '/volume'
  initial_size = '1gb'
  auto_extend_size_threshold = 85
  auto_extend_size_increment = '5GB'
  auto_extend_size_limit = '100GB'

[[mounts]]
  source = 'llamanager_models'
  destination = '/models'
  initial_size = '1gb'
  auto_extend_size_threshold = 90
  auto_extend_size_increment = '5gb'
  auto_extend_size_limit = '500gb'
  processes = ['worker']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['manager']

  [[services.ports]]
    port = 8080
    handlers = ['http']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['api']

  [[services.ports]]
    port = 8081
    handlers = ['http']

[[restart]]
  policy = 'on-failure'
  retries = 3
  processes = ['worker']

[[restart]]
  policy = 'always'
  retries = 10
  processes = ['api', 'manager']

[[vm]]
  size = 'shared-cpu-2x'
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2

[[vm]]
  size = 'performance-4x'
  memory = '32gb'
  gpu_kind = 'l40s'
  processes = ['worker']
